# Generated by Django 5.0.2 on 2024-03-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Cloth',
        ),
    ]
