# Generated by Django 5.0.2 on 2024-02-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carshop',
            options={'verbose_name': 'автомобиль', 'verbose_name_plural': 'автомобили'},
        ),
        migrations.AddField(
            model_name='carshop',
            name='drive_unit',
            field=models.CharField(choices=[('Полный', 'Полный'), ('Передний', 'Передний'), ('Задний', 'Задний')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carshop',
            name='gift',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Укажите подарок к покупке'),
            preserve_default=False,
        ),
    ]
