# Generated by Django 5.0.2 on 2024-02-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_shop', '0002_alter_carshop_options_carshop_drive_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='acceleration',
            field=models.FloatField(null=True, verbose_name='Разгон до 100км/ч:'),
        ),
        migrations.AlterField(
            model_name='carshop',
            name='year',
            field=models.IntegerField(max_length=100, null=True, verbose_name='Укажите год автомобиля'),
        ),
    ]
