# Generated by Django 5.0.2 on 2024-02-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_shop', '0004_reviewcars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcars',
            name='text',
            field=models.TextField(verbose_name='Напишите комент'),
        ),
    ]
