# Generated by Django 5.0.2 on 2024-02-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_shop', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='car_shop.reviewcars'),
            preserve_default=False,
        ),
    ]
